/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayerGUI.java
 *
 * Created on Apr 2, 2012, 12:14:15 PM
 */
package us.abaddonsoftware.titanplayer;

/**
 *
 * @author abaddon
 */
public class PlayerGUI extends javax.swing.JFrame {

    /** Creates new form PlayerGUI */
    public PlayerGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previousBtn = new javax.swing.JButton();
        playBtn = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        libraryList = new javax.swing.JList();
        volumeSlider = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        playlistList = new javax.swing.JList();
        trackNameLabel = new javax.swing.JLabel();
        artistNameLabel = new javax.swing.JLabel();
        albumNameLabel = new javax.swing.JLabel();
        remainingTimeLabel = new javax.swing.JLabel();
        totalTimeLabel = new javax.swing.JLabel();
        sortByLabel = new javax.swing.JLabel();
        currentPlaylistLabel = new javax.swing.JLabel();
        savePlaylistBtn = new javax.swing.JButton();
        delPlaylistBtn = new javax.swing.JButton();
        playlistComboBox = new javax.swing.JComboBox();
        sortComboBox = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        previousBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/abaddonsoftware/titanplayer/prev.png"))); // NOI18N
        getContentPane().add(previousBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 60, 60));

        playBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/abaddonsoftware/titanplayer/playbutton.png"))); // NOI18N
        getContentPane().add(playBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 60, 60));

        stopBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/abaddonsoftware/titanplayer/stop.png"))); // NOI18N
        getContentPane().add(stopBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 60, 60));

        nextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/abaddonsoftware/titanplayer/next.png"))); // NOI18N
        getContentPane().add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 60, 60));

        jScrollPane1.setViewportView(libraryList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 300, 460));
        getContentPane().add(volumeSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        jScrollPane2.setViewportView(playlistList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 450, 460));

        trackNameLabel.setText("TrackName");
        getContentPane().add(trackNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        artistNameLabel.setText("ArtistName");
        getContentPane().add(artistNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        albumNameLabel.setText("AlbumName");
        getContentPane().add(albumNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        remainingTimeLabel.setText("RemainingTime");
        getContentPane().add(remainingTimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        totalTimeLabel.setText("TotalTime");
        getContentPane().add(totalTimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        sortByLabel.setText("Sort by: ");
        getContentPane().add(sortByLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, -1, 30));

        currentPlaylistLabel.setText("Current Playlist: ");
        getContentPane().add(currentPlaylistLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 67, -1, 30));

        savePlaylistBtn.setText("S");
        savePlaylistBtn.setToolTipText("Save Playlist");
        getContentPane().add(savePlaylistBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 30, 30));

        delPlaylistBtn.setText("D");
        delPlaylistBtn.setToolTipText("Delete Playlist");
        getContentPane().add(delPlaylistBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 30, 30));

        playlistComboBox.setEditable(true);
        getContentPane().add(playlistComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 270, -1));

        sortComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Artist", "Track" }));
        getContentPane().add(sortComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 240, -1));

        jMenu1.setText("File");

        jMenuItem1.setText("Add To Library");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PlayerGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel albumNameLabel;
    private javax.swing.JLabel artistNameLabel;
    private javax.swing.JLabel currentPlaylistLabel;
    private javax.swing.JButton delPlaylistBtn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList libraryList;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton playBtn;
    private javax.swing.JComboBox playlistComboBox;
    private javax.swing.JList playlistList;
    private javax.swing.JButton previousBtn;
    private javax.swing.JLabel remainingTimeLabel;
    private javax.swing.JButton savePlaylistBtn;
    private javax.swing.JLabel sortByLabel;
    private javax.swing.JComboBox sortComboBox;
    private javax.swing.JButton stopBtn;
    private javax.swing.JLabel totalTimeLabel;
    private javax.swing.JLabel trackNameLabel;
    private javax.swing.JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables
}
